export const throwError = (error) => {
  console.error(error);
  process.exit(1);
};
